apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Cleaning up temporary files..."
        rm -rf /tmp/*

---

  name: nose-tests
  steps:
    - name: run-nose-tests
      image: python:3.8
      script: |
        #!/bin/bash
        pip install nose
        nosetests tests/
